apiVersion: v1
kind: Service
metadata:
  name: metadataservice
spec:
  ports:
    - name: 80-80
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: metadata
  type: NodePort