apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
    - name: 80-80
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: mongo