apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-vol-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: mongo-vol